print("Welcome to Somjing Shop")
print("Water Melon    x  ", 1, "-", 10, "THB  =", 1*10,"  THB" )
print("Avocado        x  ", 2, "-", 15, "THB  =", 2*15," THB" )
print("Lemon          x  ", 3, "-", 20, "THB  =", 3*20,"  THB" )
print("Orange         x  ", 4, "-", 25, "THB  =", 4*25,"  THB" )
print("Dragon Fruit   x  ", 5, "-", 30, "THB  =", 5*30,"  THB" )
print("Banana         x  ", 6, "-", 35, "THB  =", 6*35,"  THB" )
print("******************************************")
print("Total                    ", (1*10)+(2*15)+(3*20)+(4*25)+(5*30)+(6*35),"  THB")
print("Thank you for Shopping")